select DSE_VMPROP_PARCEL_PROPERTY.[PR_PFI] as PR_PFI,
Count(*) as VM_MultiParcCount
from DSE_VMPROP_PARCEL_PROPERTY
INNER JOIN DSE_VMPROP_PROPERTY ON DSE_VMPROP_PARCEL_PROPERTY.PR_PFI = DSE_VMPROP_PROPERTY.PROP_PFI 
WHERE DSE_VMPROP_PROPERTY.PR_PTYPE = 'O'
GROUP BY DSE_VMPROP_PARCEL_PROPERTY.[PR_PFI]
