SELECT *
FROM (SELECT [M1_MissingCouncil_Props_usingPropNo].[lga_code],
    [M1_MissingCouncil_Props_usingPropNo].[new_sub],
    [M1_MissingCouncil_Props_usingPropNo].[property_PFI],
    [M1_MissingCouncil_Props_usingPropNo].[parcel_PFI],
    [M1_MissingCouncil_Props_usingPropNo].[Address_PFI],
    [M1_MissingCouncil_Props_usingPropNo].[spi],
    [M1_MissingCouncil_Props_usingPropNo].[plan_number],
    [M1_MissingCouncil_Props_usingPropNo].[lot_number],
    [M1_MissingCouncil_Props_usingPropNo].[base_propnum],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[propnum] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[propnum],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[propnum] END as propnum,
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[crefno] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[crefno],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[crefno] END as [crefno],
    [M1_MissingCouncil_Props_usingPropNo].[hsa_flag],
    [M1_MissingCouncil_Props_usingPropNo].[hsa_unit_id],
    [M1_MissingCouncil_Props_usingPropNo].[blg_unit_type],
    [M1_MissingCouncil_Props_usingPropNo].[blg_unit_prefix_1],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[blg_unit_id_1] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[blg_unit_id_1],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[blg_unit_id_1] END as [blg_unit_id_1],
    [M1_MissingCouncil_Props_usingPropNo].[blg_unit_suffix_1],
    [M1_MissingCouncil_Props_usingPropNo].[blg_unit_prefix_2],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[blg_unit_id_2] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[blg_unit_id_2],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[blg_unit_id_2] END as [blg_unit_id_2],
    [M1_MissingCouncil_Props_usingPropNo].[blg_unit_suffix_2],
    [M1_MissingCouncil_Props_usingPropNo].[floor_type],
    [M1_MissingCouncil_Props_usingPropNo].[floor_prefix_1],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[floor_no_1] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[floor_no_1],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[floor_no_1] END as [floor_no_1],
    [M1_MissingCouncil_Props_usingPropNo].[floor_suffix_1],
    [M1_MissingCouncil_Props_usingPropNo].[floor_prefix_2],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[floor_no_2] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[floor_no_2],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[floor_no_2] END as [floor_no_2],
    [M1_MissingCouncil_Props_usingPropNo].[floor_suffix_2],
    [M1_MissingCouncil_Props_usingPropNo].[building_name],
    [M1_MissingCouncil_Props_usingPropNo].[complex_name],
    [M1_MissingCouncil_Props_usingPropNo].[location_descriptor],
    [M1_MissingCouncil_Props_usingPropNo].[house_prefix_1],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[house_number_1] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[house_number_1],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[house_number_1] END as [house_number_1],
    [M1_MissingCouncil_Props_usingPropNo].[house_suffix_1],
    [M1_MissingCouncil_Props_usingPropNo].[house_prefix_2],
    CASE WHEN [M1_MissingCouncil_Props_usingPropNo].[house_number_2] = '0' THEN REPLACE([M1_MissingCouncil_Props_usingPropNo].[house_number_2],'0','') ELSE [M1_MissingCouncil_Props_usingPropNo].[house_number_2] END as [house_number_2],
    [M1_MissingCouncil_Props_usingPropNo].[house_suffix_2],
    [M1_MissingCouncil_Props_usingPropNo].[access_type],
    [M1_MissingCouncil_Props_usingPropNo].[new_road],
    [M1_MissingCouncil_Props_usingPropNo].[road_name],
    [M1_MissingCouncil_Props_usingPropNo].[road_type],
    [M1_MissingCouncil_Props_usingPropNo].[road_suffix],
    [M1_MissingCouncil_Props_usingPropNo].[locality_name],
    [M1_MissingCouncil_Props_usingPropNo].[distance_related_flag],
    [M1_MissingCouncil_Props_usingPropNo].[is_primary],
    [M1_MissingCouncil_Props_usingPropNo].[easting],
    [M1_MissingCouncil_Props_usingPropNo].[northing],
    [M1_MissingCouncil_Props_usingPropNo].[datum/proj],
    [M1_MissingCouncil_Props_usingPropNo].[outside_property],
    [M1_MissingCouncil_Props_usingPropNo].[edit_code],
    [M1_MissingCouncil_Props_usingPropNo].[Comments]
  FROM [M1_MissingCouncil_Props_usingPropNo]
  UNION
  SELECT [M1_DifferentCouncil_Props_usingSPI].[lga_code],
    [M1_DifferentCouncil_Props_usingSPI].[new_sub],
    [M1_DifferentCouncil_Props_usingSPI].[property_PFI],
    [M1_DifferentCouncil_Props_usingSPI].[parcel_PFI],
    [M1_DifferentCouncil_Props_usingSPI].[Address_PFI],
    [M1_DifferentCouncil_Props_usingSPI].[spi],
    [M1_DifferentCouncil_Props_usingSPI].[plan_number],
    [M1_DifferentCouncil_Props_usingSPI].[lot_number],
    [M1_DifferentCouncil_Props_usingSPI].[base_propnum],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[propnum] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[propnum],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[propnum] END as propnum,
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[crefno] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[crefno],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[crefno] END as [crefno],
    [M1_DifferentCouncil_Props_usingSPI].[hsa_flag],
    [M1_DifferentCouncil_Props_usingSPI].[hsa_unit_id],
    [M1_DifferentCouncil_Props_usingSPI].[blg_unit_type],
    [M1_DifferentCouncil_Props_usingSPI].[blg_unit_prefix_1],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[blg_unit_id_1] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[blg_unit_id_1],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[blg_unit_id_1] END as [blg_unit_id_1],
    [M1_DifferentCouncil_Props_usingSPI].[blg_unit_suffix_1],
    [M1_DifferentCouncil_Props_usingSPI].[blg_unit_prefix_2],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[blg_unit_id_2] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[blg_unit_id_2],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[blg_unit_id_2] END as [blg_unit_id_2],
    [M1_DifferentCouncil_Props_usingSPI].[blg_unit_suffix_2],
    [M1_DifferentCouncil_Props_usingSPI].[floor_type],
    [M1_DifferentCouncil_Props_usingSPI].[floor_prefix_1],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[floor_no_1] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[floor_no_1],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[floor_no_1] END as [floor_no_1],
    [M1_DifferentCouncil_Props_usingSPI].[floor_suffix_1],
    [M1_DifferentCouncil_Props_usingSPI].[floor_prefix_2],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[floor_no_2] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[floor_no_2],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[floor_no_2] END as [floor_no_2],
    [M1_DifferentCouncil_Props_usingSPI].[floor_suffix_2],
    [M1_DifferentCouncil_Props_usingSPI].[building_name],
    [M1_DifferentCouncil_Props_usingSPI].[complex_name],
    [M1_DifferentCouncil_Props_usingSPI].[location_descriptor],
    [M1_DifferentCouncil_Props_usingSPI].[house_prefix_1],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[house_number_1] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[house_number_1],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[house_number_1] END as [house_number_1],
    [M1_DifferentCouncil_Props_usingSPI].[house_suffix_1],
    [M1_DifferentCouncil_Props_usingSPI].[house_prefix_2],
    CASE WHEN [M1_DifferentCouncil_Props_usingSPI].[house_number_2] = '0' THEN REPLACE([M1_DifferentCouncil_Props_usingSPI].[house_number_2],'0','') ELSE [M1_DifferentCouncil_Props_usingSPI].[house_number_2] END as [house_number_2],
    [M1_DifferentCouncil_Props_usingSPI].[house_suffix_2],
    [M1_DifferentCouncil_Props_usingSPI].[access_type],
    [M1_DifferentCouncil_Props_usingSPI].[new_road],
    [M1_DifferentCouncil_Props_usingSPI].[road_name],
    [M1_DifferentCouncil_Props_usingSPI].[road_type],
    [M1_DifferentCouncil_Props_usingSPI].[road_suffix],
    [M1_DifferentCouncil_Props_usingSPI].[locality_name],
    [M1_DifferentCouncil_Props_usingSPI].[distance_related_flag],
    [M1_DifferentCouncil_Props_usingSPI].[is_primary],
    [M1_DifferentCouncil_Props_usingSPI].[easting],
    [M1_DifferentCouncil_Props_usingSPI].[northing],
    [M1_DifferentCouncil_Props_usingSPI].[datum/proj],
    [M1_DifferentCouncil_Props_usingSPI].[outside_property],
    [M1_DifferentCouncil_Props_usingSPI].[edit_code],
    [M1_DifferentCouncil_Props_usingSPI].[Comments]
  FROM [M1_DifferentCouncil_Props_usingSPI])
UNION
SELECT [M1_MissingVM_Props_usingSPI].[lga_code],
    [M1_MissingVM_Props_usingSPI].[new_sub],
    [M1_MissingVM_Props_usingSPI].[property_PFI],
    [M1_MissingVM_Props_usingSPI].[parcel_PFI],
    [M1_MissingVM_Props_usingSPI].[Address_PFI],
    [M1_MissingVM_Props_usingSPI].[spi],
    [M1_MissingVM_Props_usingSPI].[plan_number],
    [M1_MissingVM_Props_usingSPI].[lot_number],
    [M1_MissingVM_Props_usingSPI].[base_propnum],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[propnum] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[propnum],'0','') ELSE [M1_MissingVM_Props_usingSPI].[propnum] END as propnum,
    CASE WHEN [M1_MissingVM_Props_usingSPI].[crefno] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[crefno],'0','') ELSE [M1_MissingVM_Props_usingSPI].[crefno] END as [crefno],
    [M1_MissingVM_Props_usingSPI].[hsa_flag],
    [M1_MissingVM_Props_usingSPI].[hsa_unit_id],
    [M1_MissingVM_Props_usingSPI].[blg_unit_type],
    [M1_MissingVM_Props_usingSPI].[blg_unit_prefix_1],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[blg_unit_id_1] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[blg_unit_id_1],'0','') ELSE [M1_MissingVM_Props_usingSPI].[blg_unit_id_1] END as [blg_unit_id_1],
    [M1_MissingVM_Props_usingSPI].[blg_unit_suffix_1],
    [M1_MissingVM_Props_usingSPI].[blg_unit_prefix_2],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[blg_unit_id_2] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[blg_unit_id_2],'0','') ELSE [M1_MissingVM_Props_usingSPI].[blg_unit_id_2] END as [blg_unit_id_2],
    [M1_MissingVM_Props_usingSPI].[blg_unit_suffix_2],
    [M1_MissingVM_Props_usingSPI].[floor_type],
    [M1_MissingVM_Props_usingSPI].[floor_prefix_1],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[floor_no_1] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[floor_no_1],'0','') ELSE [M1_MissingVM_Props_usingSPI].[floor_no_1] END as [floor_no_1],
    [M1_MissingVM_Props_usingSPI].[floor_suffix_1],
    [M1_MissingVM_Props_usingSPI].[floor_prefix_2],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[floor_no_2] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[floor_no_2],'0','') ELSE [M1_MissingVM_Props_usingSPI].[floor_no_2] END as [floor_no_2],
    [M1_MissingVM_Props_usingSPI].[floor_suffix_2],
    [M1_MissingVM_Props_usingSPI].[building_name],
    [M1_MissingVM_Props_usingSPI].[complex_name],
    [M1_MissingVM_Props_usingSPI].[location_descriptor],
    [M1_MissingVM_Props_usingSPI].[house_prefix_1],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[house_number_1] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[house_number_1],'0','') ELSE [M1_MissingVM_Props_usingSPI].[house_number_1] END as [house_number_1],
    [M1_MissingVM_Props_usingSPI].[house_suffix_1],
    [M1_MissingVM_Props_usingSPI].[house_prefix_2],
    CASE WHEN [M1_MissingVM_Props_usingSPI].[house_number_2] = '0' THEN REPLACE([M1_MissingVM_Props_usingSPI].[house_number_2],'0','') ELSE [M1_MissingVM_Props_usingSPI].[house_number_2] END as [house_number_2],
    [M1_MissingVM_Props_usingSPI].[house_suffix_2],
    [M1_MissingVM_Props_usingSPI].[access_type],
    [M1_MissingVM_Props_usingSPI].[new_road],
    [M1_MissingVM_Props_usingSPI].[road_name],
    [M1_MissingVM_Props_usingSPI].[road_type],
    [M1_MissingVM_Props_usingSPI].[road_suffix],
    [M1_MissingVM_Props_usingSPI].[locality_name],
    [M1_MissingVM_Props_usingSPI].[distance_related_flag],
    [M1_MissingVM_Props_usingSPI].[is_primary],
    [M1_MissingVM_Props_usingSPI].[easting],
    [M1_MissingVM_Props_usingSPI].[northing],
    [M1_MissingVM_Props_usingSPI].[datum/proj],
    [M1_MissingVM_Props_usingSPI].[outside_property],
    [M1_MissingVM_Props_usingSPI].[edit_code],
    [M1_MissingVM_Props_usingSPI].[Comments]
FROM [M1_MissingVM_Props_usingSPI]
UNION
SELECT [M1_DifferentVM_Props_usingSPI].[lga_code],
    [M1_DifferentVM_Props_usingSPI].[new_sub],
    [M1_DifferentVM_Props_usingSPI].[property_PFI],
    [M1_DifferentVM_Props_usingSPI].[parcel_PFI],
    [M1_DifferentVM_Props_usingSPI].[Address_PFI],
    [M1_DifferentVM_Props_usingSPI].[spi],
    [M1_DifferentVM_Props_usingSPI].[plan_number],
    [M1_DifferentVM_Props_usingSPI].[lot_number],
    [M1_DifferentVM_Props_usingSPI].[base_propnum],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[propnum] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[propnum],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[propnum] END as propnum,
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[crefno] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[crefno],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[crefno] END as [crefno],
    [M1_DifferentVM_Props_usingSPI].[hsa_flag],
    [M1_DifferentVM_Props_usingSPI].[hsa_unit_id],
    [M1_DifferentVM_Props_usingSPI].[blg_unit_type],
    [M1_DifferentVM_Props_usingSPI].[blg_unit_prefix_1],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[blg_unit_id_1] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[blg_unit_id_1],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[blg_unit_id_1] END as [blg_unit_id_1],
    [M1_DifferentVM_Props_usingSPI].[blg_unit_suffix_1],
    [M1_DifferentVM_Props_usingSPI].[blg_unit_prefix_2],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[blg_unit_id_2] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[blg_unit_id_2],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[blg_unit_id_2] END as [blg_unit_id_2],
    [M1_DifferentVM_Props_usingSPI].[blg_unit_suffix_2],
    [M1_DifferentVM_Props_usingSPI].[floor_type],
    [M1_DifferentVM_Props_usingSPI].[floor_prefix_1],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[floor_no_1] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[floor_no_1],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[floor_no_1] END as [floor_no_1],
    [M1_DifferentVM_Props_usingSPI].[floor_suffix_1],
    [M1_DifferentVM_Props_usingSPI].[floor_prefix_2],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[floor_no_2] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[floor_no_2],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[floor_no_2] END as [floor_no_2],
    [M1_DifferentVM_Props_usingSPI].[floor_suffix_2],
    [M1_DifferentVM_Props_usingSPI].[building_name],
    [M1_DifferentVM_Props_usingSPI].[complex_name],
    [M1_DifferentVM_Props_usingSPI].[location_descriptor],
    [M1_DifferentVM_Props_usingSPI].[house_prefix_1],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[house_number_1] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[house_number_1],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[house_number_1] END as [house_number_1],
    [M1_DifferentVM_Props_usingSPI].[house_suffix_1],
    [M1_DifferentVM_Props_usingSPI].[house_prefix_2],
    CASE WHEN [M1_DifferentVM_Props_usingSPI].[house_number_2] = '0' THEN REPLACE([M1_DifferentVM_Props_usingSPI].[house_number_2],'0','') ELSE [M1_DifferentVM_Props_usingSPI].[house_number_2] END as [house_number_2],
    [M1_DifferentVM_Props_usingSPI].[house_suffix_2],
    [M1_DifferentVM_Props_usingSPI].[access_type],
    [M1_DifferentVM_Props_usingSPI].[new_road],
    [M1_DifferentVM_Props_usingSPI].[road_name],
    [M1_DifferentVM_Props_usingSPI].[road_type],
    [M1_DifferentVM_Props_usingSPI].[road_suffix],
    [M1_DifferentVM_Props_usingSPI].[locality_name],
    [M1_DifferentVM_Props_usingSPI].[distance_related_flag],
    [M1_DifferentVM_Props_usingSPI].[is_primary],
    [M1_DifferentVM_Props_usingSPI].[easting],
    [M1_DifferentVM_Props_usingSPI].[northing],
    [M1_DifferentVM_Props_usingSPI].[datum/proj],
    [M1_DifferentVM_Props_usingSPI].[outside_property],
    [M1_DifferentVM_Props_usingSPI].[edit_code],
    [M1_DifferentVM_Props_usingSPI].[Comments]
FROM [M1_DifferentVM_Props_usingSPI]
UNION
SELECT [M1_DifferentVM_Addr_usingProps].[lga_code],
    [M1_DifferentVM_Addr_usingProps].[new_sub],
    [M1_DifferentVM_Addr_usingProps].[property_PFI],
    [M1_DifferentVM_Addr_usingProps].[parcel_PFI],
    [M1_DifferentVM_Addr_usingProps].[Address_PFI],
    [M1_DifferentVM_Addr_usingProps].[spi],
    [M1_DifferentVM_Addr_usingProps].[plan_number],
    [M1_DifferentVM_Addr_usingProps].[lot_number],
    [M1_DifferentVM_Addr_usingProps].[base_propnum],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[propnum] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[propnum],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[propnum] END as propnum,
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[crefno] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[crefno],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[crefno] END as [crefno],
    [M1_DifferentVM_Addr_usingProps].[hsa_flag],
    [M1_DifferentVM_Addr_usingProps].[hsa_unit_id],
    [M1_DifferentVM_Addr_usingProps].[blg_unit_type],
    [M1_DifferentVM_Addr_usingProps].[blg_unit_prefix_1],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[blg_unit_id_1] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[blg_unit_id_1],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[blg_unit_id_1] END as [blg_unit_id_1],
    [M1_DifferentVM_Addr_usingProps].[blg_unit_suffix_1],
    [M1_DifferentVM_Addr_usingProps].[blg_unit_prefix_2],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[blg_unit_id_2] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[blg_unit_id_2],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[blg_unit_id_2] END as [blg_unit_id_2],
    [M1_DifferentVM_Addr_usingProps].[blg_unit_suffix_2],
    [M1_DifferentVM_Addr_usingProps].[floor_type],
    [M1_DifferentVM_Addr_usingProps].[floor_prefix_1],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[floor_no_1] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[floor_no_1],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[floor_no_1] END as [floor_no_1],
    [M1_DifferentVM_Addr_usingProps].[floor_suffix_1],
    [M1_DifferentVM_Addr_usingProps].[floor_prefix_2],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[floor_no_2] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[floor_no_2],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[floor_no_2] END as [floor_no_2],
    [M1_DifferentVM_Addr_usingProps].[floor_suffix_2],
    [M1_DifferentVM_Addr_usingProps].[building_name],
    [M1_DifferentVM_Addr_usingProps].[complex_name],
    [M1_DifferentVM_Addr_usingProps].[location_descriptor],
    [M1_DifferentVM_Addr_usingProps].[house_prefix_1],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[house_number_1] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[house_number_1],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[house_number_1] END as [house_number_1],
    [M1_DifferentVM_Addr_usingProps].[house_suffix_1],
    [M1_DifferentVM_Addr_usingProps].[house_prefix_2],
    CASE WHEN [M1_DifferentVM_Addr_usingProps].[house_number_2] = '0' THEN REPLACE([M1_DifferentVM_Addr_usingProps].[house_number_2],'0','') ELSE [M1_DifferentVM_Addr_usingProps].[house_number_2] END as [house_number_2],
    [M1_DifferentVM_Addr_usingProps].[house_suffix_2],
    [M1_DifferentVM_Addr_usingProps].[access_type],
    [M1_DifferentVM_Addr_usingProps].[new_road],
    [M1_DifferentVM_Addr_usingProps].[road_name],
    [M1_DifferentVM_Addr_usingProps].[road_type],
    [M1_DifferentVM_Addr_usingProps].[road_suffix],
    [M1_DifferentVM_Addr_usingProps].[locality_name],
    [M1_DifferentVM_Addr_usingProps].[distance_related_flag],
    [M1_DifferentVM_Addr_usingProps].[is_primary],
    [M1_DifferentVM_Addr_usingProps].[easting],
    [M1_DifferentVM_Addr_usingProps].[northing],
    [M1_DifferentVM_Addr_usingProps].[datum/proj],
    [M1_DifferentVM_Addr_usingProps].[outside_property],
    [M1_DifferentVM_Addr_usingProps].[edit_code],
    [M1_DifferentVM_Addr_usingProps].[Comments]
FROM [M1_DifferentVM_Addr_usingProps]
ORDER BY [Property_PFI],[propnum]
